### ISSUE TITLE
patch_train_val.txt missing

### ISSUE THREAD

**Issue by LukasMosser** [yalaudah/facies_classification_benchmark#1]
I've tried running the training part as suggested in the readme, but it seems your training validation splits are missing from the data/repository.

Could you add these files, or point me to where I can obtain these?
```
Traceback (most recent call last):
  File "patch_train.py", line 375, in <module>
    train(args)
  File "patch_train.py", line 84, in train
    split_train_val(args, per_val=args.per_val)
  File "patch_train.py", line 68, in split_train_val
    pjoin('data', 'splits', loader_type + '_train_val.txt'), 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'data/splits/patch_train_val.txt'
```

**Comment by yalaudah** [comment]
Hi @Lukas, the training/validation splits are generated automatically. However, you should create a `/splits` directory inside the `/data` folder. This would be easy to fix on your end, and I will add code to automatically add that folder if it doesn't exist.

**Comment by yalaudah** [comment]
I've updated the instructions in the README to explicitly add a `splits` directory. I will close this for now, but If you still face any further issues, let me know.

**Comment by LukasMosser** [comment]
Ah Thanks! I wasn't clear on that it was being made at runtime. Many thanks.
