### ISSUE TITLE
SEGY version of raw data

### ISSUE THREAD

**Issue by FJGEODEV** [yalaudah/facies_classification_benchmark#12]
Hi Alaudah,

Thanks for sharing data and results. I am wondering if you have SEGY version of raw seismic data and label instead of numpy format.

Thanks.

**Comment by FJGEODEV** [comment]
Raw data means data in raw.zip you provided from your dropbox address. Thanks.

**Comment by yalaudah** [comment]
Hi @FanJiangDev 

We don't provide the SEGY data for either the seismic or the labels as its heavily processed before we generate the numpy volumes. If you're interested you can find the raw segy of the F3 block (but migrated in time, not depth) on dGB's website.
