### ISSUE TITLE
¿Is there possibility of generating horizons and fault detection with Deep Learning in Python?

### ISSUE THREAD

**Issue by YosmelyBermudez** [yalaudah/facies_classification_benchmark#13]
Hello! I have loved his work with facies and machine learning. I am currently doing my undergraduate work to obtain a Geophysical Engineering degree, and my project is based on the use of supervised and unsupervised neural networks to recognize facies and petrophysical  attributes. At the moment I am working with the Opendtect and H&R programs but right now I am looking for a Python library that can automate the generation of Horizons and fault detection in seismic (which I am working on in time). I would really appreciate if you have any suggestions in this regard. @yalaudah

**Comment by yalaudah** [comment]
Hi @YosmelyBermudez.. I'm not aware of any open source Python library that can do this at the moment, but I know Xinming Wu has done some work in generating synthetic seismic data for training deep learning models  (https://www.jsg.utexas.edu/wu/latest-publication/). He might be able to help. 🙂

**Comment by YosmelyBermudez** [comment]
Thanks so much! it is helpfull!
