### ISSUE TITLE
How to get 'data\\splits\\section_train_val.txt', please?

### ISSUE THREAD

**Issue by jiaweihuajason** [yalaudah/facies_classification_benchmark#15]
Hello, Thanks for your great code for seismic facies classification. It an useful work for my research.

But, when I try it, a problem appered like follow figure. 
![image](https://user-images.githubusercontent.com/43205783/115521379-aecb2680-a2bd-11eb-8c72-08dc536b2513.png)

I think that I miss a file name "data\\splits\\section_train_val.txt". however, I dont know how to get it.

Please Help Me！
Look Forward to Your Reply.

**Comment by yalaudah** [comment]
@jiaweihuajason It seems to me the issue is because you're running this on a Windows machine. You can manually adjust the line 48 in `section_train.py` to include the full path instead of the relative path to the `data/splits` directory. That should fix it.
