### ISSUE TITLE
Issue in section_test.py 

### ISSUE THREAD

**Issue by motazalfarraj** [yalaudah/facies_classification_benchmark#16]
In section test, line#28: 

`splits = [args.split if 'both' not in args.split else 'test1', 'test2']`

when args.split = "test2", the output split will be ["test2", "test2"] 
when args.split = "test1", the output split will be ["test1", "test2"] 

@yalaudah

**Comment by yalaudah** [comment]
Thanks! that's interesting that I didn't pick this up before. I think it's missing extra brackets for ['test1', 'test2'].

**Comment by yalaudah** [comment]
@motazalfarraj I'm closing this issue as it has been fixed in PR #17. Thanks again for pointing this out!
